### ISSUE TITLE
Finding collection return Flexirest::ResponseParseException

### ISSUE THREAD

**Issue by Congrammers** [mkhairi/billplz-api#3]
`collection = Billplz::Collection.find("collectionidhere")
`

returned
```
Flexirest::Base Base URL set to be https://billplz.com/api/v3
  Flexirest Billplz::Collection:/collections/collectionidhere - Trying to read from cache
  Flexirest Billplz::Collection#find - Requesting https://billplz.com/api/v3/collections/collectionidhere
  Flexirest (1131.7ms) Billplz::Collection#find
Flexirest::ResponseParseException: Flexirest::ResponseParseException
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/flexirest-1.3.33/lib/flexirest/request.rb:418:in `handle_response'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/flexirest-1.3.33/lib/flexirest/request.rb:213:in `block (2 levels) in call'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/flexirest-1.3.33/lib/flexirest/request.rb:194:in `block in call'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `instrument'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/flexirest-1.3.33/lib/flexirest/request.rb:150:in `call'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/flexirest-1.3.33/lib/flexirest/mapping.rb:46:in `_call'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/flexirest-1.3.33/lib/flexirest/mapping.rb:28:in `block in _map_call'
	from (irb):1
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/console.rb:65:in `start'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by mkhairi** [comment]
seem like the response is unparsable.
try debug with some exception.

```
begin
  collection = Billplz::Collection.find("collectionidhere")
rescue Flexirest::ResponseParseException => e
  Rails.logger.error("API returned #{e.status} : #{e.result.message}")
end

```

**Comment by Congrammers** [comment]
```
begin
  collection = Billplz::Collection.find("s2eaqiso")
rescue Flexirest::ResponseParseException => e
  Rails.logger.error("API returned #{e.status} : #{e.result.message}")
end
```

irb(main):011:1* irb(main):012:1> irb(main):013:1> irb(main):014:1> Flexirest::Base Base URL set to be https://billplz.com/api/v3
  Flexirest Billplz::Collection:/collections/s2eaqiso - Trying to read from cache
  Flexirest Billplz::Collection#find - Requesting https://billplz.com/api/v3/collections/s2eaqiso
  Flexirest (1236.3ms) Billplz::Collection#find
NoMethodError: undefined method `result' for #<Flexirest::ResponseParseException:0x0055c8384155e0>
	from (irb):13:in `rescue in irb_binding'
	from (irb):10
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by Congrammers** [comment]
is flexirest viable option? 

https://github.com/flexirest/flexirest/issues/64

**Comment by mkhairi** [comment]
@Congrammers .. 

```
Flexirest::Base Base URL set to be https://billplz.com/api/v3
  Flexirest Billplz::Collection:/collections/collectionidhere - Trying to read from cache
  Flexirest Billplz::Collection#find - Requesting https://billplz.com/api/v3/collections/collectionidhere
  Flexirest (1131.7ms) Billplz::Collection#find
```

your billplz api url is invalid. www is missing. 


```https://billplz.com/api/v3``` ---> ```https://www.billplz.com/api/v3```

**Comment by Congrammers** [comment]
silly me, very good gem bos.
